import { Sparkles, Loader2 } from "lucide-react";

interface SmartRepliesProps {
  suggestions: string[];
  onSelect: (text: string) => void;
  loading?: boolean;
}

/**
 * Renders a row of contextual quick-reply chips generated by Gemini.
 * Shows a loading skeleton while the AI is analyzing the conversation.
 * Renders nothing when there are no suggestions and not loading.
 */
const SmartReplies = ({ suggestions, onSelect, loading = false }: SmartRepliesProps) => {
  if (!loading && suggestions.length === 0) return null;

  return (
    <div className="px-3 py-2 border-t bg-muted/20">
      <div className="flex items-center gap-1.5 mb-1.5">
        {loading ? (
          <Loader2 className="h-3 w-3 text-primary animate-spin" />
        ) : (
          <Sparkles className="h-3 w-3 text-primary" />
        )}
        <span className="text-[11px] text-muted-foreground font-medium tracking-wide uppercase">
          {loading ? "Analisando conversa..." : "Sugestões inteligentes"}
        </span>
      </div>

      <div className="flex flex-wrap gap-1.5">
        {loading ? (
          // Skeleton chips
          [80, 110, 95].map((w) => (
            <div
              key={w}
              className="h-6 rounded-full bg-muted animate-pulse"
              style={{ width: w }}
            />
          ))
        ) : (
          suggestions.map((text) => (
            <button
              key={text}
              type="button"
              onClick={() => onSelect(text)}
              className="text-[12px] px-3 py-1 rounded-full border border-primary/30 bg-primary/5 text-primary
                         hover:bg-primary/15 hover:border-primary/50 active:scale-95
                         transition-all duration-150 cursor-pointer leading-snug"
            >
              {text}
            </button>
          ))
        )}
      </div>
    </div>
  );
};

export default SmartReplies;
